### ISSUE TITLE
使用代理会报错

### ISSUE THREAD

**Issue by overblued-cat** [e68862230/animeRssDownload#1]
使用代理会报错
![image](https://user-images.githubusercontent.com/60591802/154688091-dceaee51-5075-45c0-9049-d2891f75e247.png)
不使用代理连不上
![image](https://user-images.githubusercontent.com/60591802/154688140-a609b203-2a96-4890-a423-0523bb9da49e.png)

**Comment by e68862230** [comment]
Hmmm...建议直接改一下tmdb的host，这样就不要用代理了。用代理报错的原因大概是clash没有把协议一起转发。。

**Comment by overblued-cat** [comment]
emmmm改了hosts以后变成这样了
![image](https://user-images.githubusercontent.com/60591802/154696996-767bc787-781d-48ce-a403-7adc06406062.png)

**Comment by e68862230** [comment]
这样好像是成功了0.0

**Comment by e68862230** [comment]
你settings.json里tmdb的api_key填了么？

**Comment by overblued-cat** [comment]
填了

**Comment by e68862230** [comment]
api.themoviedb.org/3/tv/1429?language=zh-CN&api_key=  这个链接能正常返回内容吗

**Comment by overblued-cat** [comment]
打得开，是巨人吧

**Comment by e68862230** [comment]
抱歉，之前改的忘记上传了，api_Key那边少加了个global，重新下载main.py应该可以了
